- name: Install nullmailer package
  apt: name=nullmailer state=present

- name: Enable nullmailer
  service: name=nullmailer state=started enabled=yes

- name: Configure nullmailer adminaddr
  copy: content="{{ nullmailer.adminaddr }}\n"
        dest=/etc/nullmailer/adminaddr
  notify:
    - Restart nullmailer

- name: Configure nullmailer defaultdomain
  copy: content="{{ nullmailer.defaultdomain }}\n"
        dest=/etc/nullmailer/defaultdomain
  notify:
    - Restart nullmailer

- name: Configure nullmailer remotes
  template: src=remotes.j2 dest=/etc/nullmailer/remotes
            owner=mail group=mail mode=0600
  notify:
    - Restart nullmailer
