- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    aws_region: eu-central-1
    aws_ami_image: ami-429d5a2d
    aws_key_pair: loki-key
    aws_ebs_volume: loki-home
    aws_eip: 35.156.200.112
  tasks:
    - name: Install boto
      pip: name=boto state=present

    - name: Create key pair
      ec2_key:
        name: loki-key
        key_material: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
        region: "{{ aws_region }}"

    - name: Full outgoing security group
      ec2_group:
        name: full_outgoing
        description: Allow connections to anywhere
        region: "{{ aws_region }}"
        rules_egress:
          - proto: all
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0

    - name: SSH security group
      ec2_group:
        name: ssh
        description: Allow SSH from anywhere
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: SMTP security group
      ec2_group:
        name: smtp
        description: Allow SMTP from anywhere
        region: "{{ aws_region }}"
        rules:
          - proto: tcp
            from_port: 25
            to_port: 25
            cidr_ip: 0.0.0.0/0

    - name: Create loki instance
      ec2:
        instance_type: t2.micro
        image: "{{ aws_ami_image }}"
        key_name: "{{ aws_key_pair }}"
        groups:
          - full_outgoing
          - ssh
          - smtp
        instance_tags:
          loki: "true"
          Name: loki
        region: "{{ aws_region }}"
        exact_count: 1
        count_tag:
          loki: "true"
        wait: True
      register: ec2

    - name: Attach home EBS volume
      ec2_vol:
        device_name: /dev/sdb
        encrypted: True
        name: "{{ aws_ebs_volume }}"
        instance: "{{ item.id }}"
        region: "{{ aws_region }}"
        volume_size: 20
        volume_type: gp2
      with_items: "{{ ec2.instances }}"

    - name: Attach elastic IP
      ec2_eip:
        device_id: "{{ item.id }}"
        ip: "{{ aws_eip }}"
        region: "{{ aws_region }}"
      with_items: "{{ ec2.instances }}"
