---
- name: Mount /home
  mount:
    name: /home
    src: UUID=6131f13d-ea01-4ed7-9dcf-c6082c742799
    boot: True
    fstype: ext4
    state: mounted

- name: Configure hostname
  copy: content="{{ hostname.fqdn }}{{'\n'}}"
        dest=/etc/hostname
        owner=root group=root mode=0644
  register: hostname_file
  
- name: Set hostname
  command: /bin/hostname {{ hostname.fqdn }}
  when: hostname_file.changed        

- name: Activate useful locales
  locale_gen: name={{ item }} state=present
  register: locale_gen_file
  with_items:
    - de_DE.UTF-8
    - en_US.UTF-8

- name: Generate locales
  command: /usr/sbin/locale-gen
  when: locale_gen_file.changed

- name: Set default locale
  copy: content='LANG="en_US.UTF-8"'
        dest=/etc/default/locale
        owner=root group=root mode=0644

- name: Create journal directory
  file: name=/var/log/journal
        state=directory
        owner=root group=systemd-journal mode=2755

- name: Disable root login in ssh
  lineinfile: dest=/etc/ssh/sshd_config
              regexp=^PermitRootLogin
              line="PermitRootLogin no"
  notify:
    - Restart sshd

- name: Allow only admin user to log in
  lineinfile: dest=/etc/ssh/sshd_config
              regexp=^AllowUsers
              line="AllowUsers admin {{ personal.user.name }}"
  notify:
    - Restart sshd

- name: Enable challenge-based login
  lineinfile: dest=/etc/ssh/sshd_config
              regexp=^ChallengeResponseAuthentication
              line="ChallengeResponseAuthentication yes"
  notify:
    - Restart sshd

- name: Disable the Debian banner in sshd
  lineinfile: dest=/etc/ssh/sshd_config
              regexp=^DebianBanner
              line="DebianBanner no"
  notify:
    - Restart sshd

- name: Disable installing recommended packages
  template: src=10norecommends.j2 dest=/etc/apt/apt.conf.d/10norecommends
            owner=root group=root mode=0644

- name: Deinstall rsyslog
  apt: name=rsyslog state=absent purge=yes

- name: Remove rsyslog log files
  file: name={{ item }} state=absent
  with_items:
    - /var/log/auth.log
    - /var/log/syslog
    - /var/log/cron.log
    - /var/log/daemon.log
    - /var/log/kern.log
    - /var/log/lpr.log
    - /var/log/mail.log
    - /var/log/user.log
    - /var/log/mail.info
    - /var/log/mail.warn
    - /var/log/mail.err
    - /var/log/debug
    - /var/log/messages

- name: Install unattended-upgrades
  apt: name=unattended-upgrades state=present

- name: create APT auto-upgrades configuration
  copy: src=auto-upgrades
        dest=/etc/apt/apt.conf.d/20auto-upgrades
        owner=root group=root mode=0644

- name: create unattended-upgrades configuration
  template: src=unattended-upgrades.j2
            dest=/etc/apt/apt.conf.d/50unattended-upgrades
            owner=root group=root mode=0644
