- name: Set hostname
  hostname: name={{ hostname.fqdn }}

- name: Configure /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts
            owner=root group=root mode=0644

- name: Install fail2ban
  apt: name=fail2ban state=present

- name: Enable fail2ban
  service: name=fail2ban state=started enabled=yes
