# Host name
- name: Set hostname
  hostname: name={{ hostname.fqdn }}

- name: Configure /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts
            owner=root group=root mode=0644

# Debian configuration
- name: Disable installing recommended packages
  template: src=10norecommends.j2 dest=/etc/apt/apt.conf.d/10norecommends
            owner=root group=root mode=0644

# fail2ban
- name: Install fail2ban
  apt: name=fail2ban state=present

- name: Enable fail2ban
  service: name=fail2ban state=started enabled=yes

# ssh
- name: Disable root login in ssh
  lineinfile: dest=/etc/ssh/sshd_config
              regexp=^PermitRootLogin
              line="PermitRootLogin no"
  notify:
    - Restart sshd

- name: Allow only forcer to log in
  lineinfile: dest=/etc/ssh/sshd_config
              regexp=^AllowUsers
              line="AllowUsers forcer"
  notify:
    - Restart sshd

- name: Disable the Debian banner in sshd
  lineinfile: dest=/etc/ssh/sshd_config
              regexp=^DebianBanner
              line="DebianBanner no"
  notify:
    - Restart sshd

- name: Enable root logins from localhost
  blockinfile:
    dest: /etc/ssh/sshd_config
    block: |
      Match Address 127.0.0.1,{{ansible_default_ipv4.address}},{{ansible_default_ipv6.address}}
        PermitRootLogin yes
        AllowUsers forcer root
  notify:
    - Restart sshd
