---
hostname:
  fqdn: loki.jorgenschaefer.de
  short: loki

personal:
  user:
    name: forcer
    comment: Jorgen Schaefer

# mail:
nullmailer:
  adminaddr: Jorgen.Schaefer@gmail.com
  defaultdomain: jorgenschaefer.de
  remote_host: smtp.gmail.com
  remote_user: Jorgen.Schaefer@gmail.com
  remote_password: "{{ vault_nullmailer_remote_password }}"

smtpproxy:
  valid_recipients: |
    "^(forcer|jorgen|contact)@(jorgenschaefer\.de|forcix\.cx)$"
  override_recipient: |
    "Jorgen.Schaefer@gmail.com"
  relay_host: |
    "gmail-smtp-in.l.google.com:25"

# web:
certificates:
  www_jorgenschaefer_de:
    key: "{{ vault_www_jorgenschaefer_de_private_key }}"
    pem: |
      -----BEGIN CERTIFICATE-----
      MIIGVzCCBT+gAwIBAgIHBn1RXmPBbzANBgkqhkiG9w0BAQsFADCBjDELMAkGA1UE
      BhMCSUwxFjAUBgNVBAoTDVN0YXJ0Q29tIEx0ZC4xKzApBgNVBAsTIlNlY3VyZSBE
      aWdpdGFsIENlcnRpZmljYXRlIFNpZ25pbmcxODA2BgNVBAMTL1N0YXJ0Q29tIENs
      YXNzIDEgUHJpbWFyeSBJbnRlcm1lZGlhdGUgU2VydmVyIENBMB4XDTE1MTAyNDE1
      MjEzMloXDTE2MTAyNDE1MDYxM1owWjELMAkGA1UEBhMCREUxHjAcBgNVBAMTFXd3
      dy5qb3JnZW5zY2hhZWZlci5kZTErMCkGCSqGSIb3DQEJARYccG9zdG1hc3RlckBq
      b3JnZW5zY2hhZWZlci5kZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
      ANRZ8q+BREA1BiczVlzbwF7RqAqbFV4LmzL6NQAMIt0+ZAt/BSsubRACem0qqwke
      cGPN+JCBHGgotuaqtglQPmUMkyQWKX9mcm8vU3yY9QXOJIYNuU1NRL8Sig4wohGa
      z7NGYWT69U0f9ELPr5M3t9urZfIRwm53fevXZSXkMzSf1BDLFdwWjO55bhM+fC/m
      mPriN1F10C7GC9nQxWSPH8+8M+527XNOYRts1vpnB7prWrqh5zHeWyQ/xQRzVbpV
      1DVSOyuIztCr3syW8NYAFxi/65cnu7ZUWMr3OcLaCpui9REJDgQLPvG5A/VKcCIe
      lnwcpfgIcrJqcloJhEUZpY0CAwEAAaOCAu0wggLpMAkGA1UdEwQCMAAwCwYDVR0P
      BAQDAgOoMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB0GA1UdDgQWBBQZkZ3uTH9k5phZ
      XnPSMfDta0UiMTAfBgNVHSMEGDAWgBTrQjTQmLCrn/Qbawj3zGQu7w4sRTAzBgNV
      HREELDAqghV3d3cuam9yZ2Vuc2NoYWVmZXIuZGWCEWpvcmdlbnNjaGFlZmVyLmRl
      MIIBVgYDVR0gBIIBTTCCAUkwCAYGZ4EMAQIBMIIBOwYLKwYBBAGBtTcBAgMwggEq
      MC4GCCsGAQUFBwIBFiJodHRwOi8vd3d3LnN0YXJ0c3NsLmNvbS9wb2xpY3kucGRm
      MIH3BggrBgEFBQcCAjCB6jAnFiBTdGFydENvbSBDZXJ0aWZpY2F0aW9uIEF1dGhv
      cml0eTADAgEBGoG+VGhpcyBjZXJ0aWZpY2F0ZSB3YXMgaXNzdWVkIGFjY29yZGlu
      ZyB0byB0aGUgQ2xhc3MgMSBWYWxpZGF0aW9uIHJlcXVpcmVtZW50cyBvZiB0aGUg
      U3RhcnRDb20gQ0EgcG9saWN5LCByZWxpYW5jZSBvbmx5IGZvciB0aGUgaW50ZW5k
      ZWQgcHVycG9zZSBpbiBjb21wbGlhbmNlIG9mIHRoZSByZWx5aW5nIHBhcnR5IG9i
      bGlnYXRpb25zLjA1BgNVHR8ELjAsMCqgKKAmhiRodHRwOi8vY3JsLnN0YXJ0c3Ns
      LmNvbS9jcnQxLWNybC5jcmwwgY4GCCsGAQUFBwEBBIGBMH8wOQYIKwYBBQUHMAGG
      LWh0dHA6Ly9vY3NwLnN0YXJ0c3NsLmNvbS9zdWIvY2xhc3MxL3NlcnZlci9jYTBC
      BggrBgEFBQcwAoY2aHR0cDovL2FpYS5zdGFydHNzbC5jb20vY2VydHMvc3ViLmNs
      YXNzMS5zZXJ2ZXIuY2EuY3J0MCMGA1UdEgQcMBqGGGh0dHA6Ly93d3cuc3RhcnRz
      c2wuY29tLzANBgkqhkiG9w0BAQsFAAOCAQEAsl8wn9speeAlX7nu4ArDib6W2R1z
      9dJZMKgiTw6noVsETUcoNFru5LN2mYA8EI3j0WRurd5pgdJ3AvgUTIoZn1dJyFqd
      5gZDm5Y2g2c8H8Nuoo0KNsazdqedUinldIUKqh7G+rt6XS4bOMMrfAMrOTOO9+kv
      bXXq+ZADbnJz4Y+bSFy4Re77dpyfHzV8gEQguiFGxYbVeMR7QbF/adKzVgIBLlfD
      74s0O1wNAN4mm0fefNL9C3ug3i3T0OBJgz/zLzIBiybzHmaYGlc8tx3vFoVDMB3b
      ejaLth4kdYYNbiBP+FFZN8nynG5OiKQR7Ev/iyw6woLKfZ/XpmtP2E399Q==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIF2TCCA8GgAwIBAgIHFxU9nqs/vzANBgkqhkiG9w0BAQsFADB9MQswCQYDVQQG
      EwJJTDEWMBQGA1UEChMNU3RhcnRDb20gTHRkLjErMCkGA1UECxMiU2VjdXJlIERp
      Z2l0YWwgQ2VydGlmaWNhdGUgU2lnbmluZzEpMCcGA1UEAxMgU3RhcnRDb20gQ2Vy
      dGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMDcxMDE0MjA1NDE3WhcNMjIxMDE0MjA1
      NDE3WjCBjDELMAkGA1UEBhMCSUwxFjAUBgNVBAoTDVN0YXJ0Q29tIEx0ZC4xKzAp
      BgNVBAsTIlNlY3VyZSBEaWdpdGFsIENlcnRpZmljYXRlIFNpZ25pbmcxODA2BgNV
      BAMTL1N0YXJ0Q29tIENsYXNzIDEgUHJpbWFyeSBJbnRlcm1lZGlhdGUgU2VydmVy
      IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtonGrO8JUngHrJJj
      0PREGBiEgFYfka7hh/oyULTTRwbw5gdfcA4Q9x3AzhA2NIVaD5Ksg8asWFI/ujjo
      /OenJOJApgh2wJJuniptTT9uYSAK21ne0n1jsz5G/vohURjXzTCm7QduO3CHtPn6
      6+6CPAVvkvek3AowHpNz/gfK11+AnSJYUq4G2ouHI2mw5CrY6oPSvfNx23BaKA+v
      WjhwRRI/ME3NO68X5Q/LoKldSKqxYVDLNM08XMML6BDAjJvwAwNi/rJsPnIO7hxD
      KslIDlc5xDEhyBDBLIf+VJVSH1I8MRKbf+fAoKVZ1eKPPvDVqOHXcDGpxLPPr21T
      Lwb0pwIDAQABo4IBTDCCAUgwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8E
      BAMCAQYwHQYDVR0OBBYEFOtCNNCYsKuf9BtrCPfMZC7vDixFMB8GA1UdIwQYMBaA
      FE4L7xqkQFulF2mHMMo0aEPQQa7yMGkGCCsGAQUFBwEBBF0wWzAnBggrBgEFBQcw
      AYYbaHR0cDovL29jc3Auc3RhcnRzc2wuY29tL2NhMDAGCCsGAQUFBzAChiRodHRw
      Oi8vYWlhLnN0YXJ0c3NsLmNvbS9jZXJ0cy9jYS5jcnQwMgYDVR0fBCswKTAnoCWg
      I4YhaHR0cDovL2NybC5zdGFydHNzbC5jb20vc2ZzY2EuY3JsMEMGA1UdIAQ8MDow
      OAYEVR0gADAwMC4GCCsGAQUFBwIBFiJodHRwOi8vd3d3LnN0YXJ0c3NsLmNvbS9w
      b2xpY3kucGRmMA0GCSqGSIb3DQEBCwUAA4ICAQCBnsOw7dxamNbdJb/ydkh4Qb6E
      qgEU+G9hCCIGXwhWRZMYczNJMrpVvyLq5mNOmrFPC7bJrqYV+vEOYHNXrzthLyOG
      FFOVQe2cxbmQecFOvbkWVlYAIaTG42sHKVi+RFsG2jRNZcFhHnsFnLPMyE6148lZ
      wVdZGsxZvpeHReNUpW0jh7uq90sShFzHs4f7wJ5XmiHOL7fZbnFV6uE/OoFnBWif
      CRnd9+RE3uCospESPCRPdbG+Q4GQ+MBS1moXDTRB6DcNoHvqC6eU3r8/Fn/DeA9w
      9JHPXUfrAhZYKyOQUIqcfE5bvssaY+oODVxji6BMk8VSVHsJ4FSC1/7Pkt/UPoQp
      FVh38wIJnvEUeNVmVl3HHFYTd50irdKYPBC63qi2V/YYI6bJKmbrjfP9Vhyt9uNr
      y3Kh4W22ktDuCCvWC7n/gqerdq+VlTRfNt7D/mB0irnaKjEVNCXBXm9V/978J+Ez
      8aplGZccQ9jnc9kiPtUp5dj45E3V8vKqzp9srSSI5Xapdg+ZcPY+6HNuVB+MadRp
      ZW2One/Qnzg9B4GnVX7MOETImdoP4kXpostFuxoY/5LxCU1LJAIENV4txvT50lX2
      GBXCkxllRLWOgdyll11ift/4IO1aCOGDijGIfh498YisM1LGxytmGcxvbJERVri+
      gGpWAZ5J6dvtf0s+bA==
      -----END CERTIFICATE-----
    dhparam: |
      -----BEGIN DH PARAMETERS-----
      MIIBCAKCAQEA+OeL2nIrhSo2o3AhnLG0KTlILUicrAeHIecNZz9ixR1Ol9eA8neW
      1Sn3OKcrQ04l9/8vdC0Vt5fgWZ3ws8D1HW5do7U161w5J4PwXbfTMke7lvG1tecd
      DHw20+TjejuQN5kgId/eN+q10F4I5t5Zor/k/jIlhruzIjYk3S5jgvYjko8YYhZ9
      LvfhTP0TQAt29KzxWvPv3ChSw4ZZV/sxPdDX2mjPEmZFIi5WS5THMopLECYEo016
      5n6FIZ2sMW9nW8d9G44b/sEokjpzLGMLEZhBzqOKuZ/dA/wLgScBzogv00Y1oRo7
      XCOX+AoiZ1JGKze1cYhfSnamfKFr+JpI6wIBAg==
      -----END DH PARAMETERS-----
