---
hostname: loki.jorgenschaefer.de

personal:
  user:
    name: forcer
    comment: Jorgen Schaefer

# mail:
nullmailer:
  adminaddr: Jorgen.Schaefer@gmail.com
  defaultdomain: jorgenschaefer.de
  remote_host: smtp.gmail.com
  remote_user: Jorgen.Schaefer@gmail.com
  remote_password: "{{ vault_nullmailer_remote_password }}"
