---
hostname:
  fqdn: loki.jorgenschaefer.de
  short: loki

personal:
  user:
    name: forcer
    comment: Jorgen Schaefer
    password: "{{ secret_user_password }}"

nullmailer:
  adminaddr: Jorgen.Schaefer@gmail.com
  defaultdomain: jorgenschaefer.de
  remote_host: smtp.gmail.com
  remote_user: Jorgen.Schaefer@gmail.com
  remote_password: "{{ secret_nullmailer_remote_password }}"

smtpproxy:
  valid_recipients: |
    "^(forcer|jorgen|contact)@(jorgenschaefer\.de|forcix\.cx)$"
  override_recipient: |
    "Jorgen.Schaefer@gmail.com"
  relay_host: |
    "gmail-smtp-in.l.google.com:25"

journalcheck_recipient: Jorgen.Schaefer@gmail.com
